---
- name: Collect all BIG-IP facts
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Collect all BIG-IP facts
      bigip_device_facts:
        gather_subset:
          - all
      delegate_to: localhost
