satellite_user: admin
satellite_pass: dummy
satellite_hostname: sat6.summit.example.com
activation_key: rhel7beta
organization: Default Organization
location: Default Location
hostgroup: base_with_puppet_75
updatehost: false
