---
- name: Set Up Repos
  shell: "{{ item }}"
  register: sat_repos_output
  with_items:
    - subscription-manager repos --enable rhel-7-server-extras-beta-rpms

- name: Log sat_repos_output
  debug:
    var: sat_repos_output
  when: verbose and sat_repos_output is defined

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - scap-security-guide
    - rubygem-foreman_scap_client
    - ansible
    - redhat-access-insights

#- name: Configure Red Hat Access Insights
#  command: "{{ item }}"
#  with_items:
#    - "redhat-access-insights --register"

- name: Insert ignore_errors into plays
  replace:
    path: "/usr/share/scap-security-guide/ansible/{{ scap_profile_name }}.yml"
    regexp: '(^\s.*- name:.*)'
    replace: '\1\n      ignore_errors: true'
    backup: yes
  register: replace_output

- name: Log replace_output
  debug:
    var: replace_output
  when: verbose and replace_output is defined

- name: Run SCAP remediation playbook
  shell: "ansible-playbook -i localhost, -c local /usr/share/scap-security-guide/ansible/{{ scap_profile_name }}.yml"
  register: scap_output
  when: scap_profile_name is defined

- name: Log scap_output
  debug:
    var: scap_output
  when: verbose and scap_output is defined

# Add your own plays here
